// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxguJLPnGKiPleJgKxmQYjo4DpPTUmW50',
    appId: '1:51357316925:web:bd875540f8d8ce14fab754',
    messagingSenderId: '51357316925',
    projectId: 'expensesone',
    authDomain: 'expensesone.firebaseapp.com',
    storageBucket: 'expensesone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKOdvh9xkiZkWBgDgqmpZqBBrLRg5ztbc',
    appId: '1:51357316925:android:cbe8347c91b6e34cfab754',
    messagingSenderId: '51357316925',
    projectId: 'expensesone',
    storageBucket: 'expensesone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNmeq_r45m0cc5mEjm2lC21A0xxZ1667I',
    appId: '1:51357316925:ios:52ba22bb6b86acb3fab754',
    messagingSenderId: '51357316925',
    projectId: 'expensesone',
    storageBucket: 'expensesone.appspot.com',
    iosBundleId: 'com.myexpensetraker.myexpensetraker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNmeq_r45m0cc5mEjm2lC21A0xxZ1667I',
    appId: '1:51357316925:ios:e0d67febd350a6abfab754',
    messagingSenderId: '51357316925',
    projectId: 'expensesone',
    storageBucket: 'expensesone.appspot.com',
    iosBundleId: 'com.myexpensetraker.myexpensetraker.RunnerTests',
  );
}
